### ISSUE TITLE
`<a-entity>` is causing me to mistype "entities" as "entitities" several times a day

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-core#571]
I know how to spell, but there are so many `t`s and `i`s in `entity` and `entities`.

> #   
> # :athletic_shoe::gun: 
> #

**Comment by ngokevin** [comment]
Duly noted, but not actionable. I think we're doing okay with "entity", I've heard developers that have dove in like it or are faring well with it.

**Comment by jcarpenter** [comment]
Agreed. This is shipping and documented thoroughly. We've made our bed and will sleep in it :)
