### ISSUE TITLE
Add "walk" user movement

### ISSUE THREAD

**Issue by jcarpenter** [aframevr/aframe-core#6]
User can:

* Walk fwd / backward
* Run fwd / backward
* Strafe left, strafe right
* Jump

Supported input devices:

* Keyboard support
* Gamepad support `lower priority`

Supported customizable attributes (passed as arguments via element attribute?)

* Run speed
* Walk speed
* Jump strength
* eg `<vr-playerWalk runSpeed="20" walkSpeed="10" jumpStrength="1"></vr-playerWalk>`

Need to decide how we want to implement this. For example:

* Import JS
* Import JS _and_ create child node within scene

TODO: need to investigate effective player walking controls for virtual reality. Animated pseudo head-bobbing is a big no-no, for example.

**Comment by jcarpenter** [comment]
Initial implementation is in place and working well. @caseyyee is looking at optimizing the VR mode version of the controls to better fit the ergonomics of VR.

**Comment by sirkitree** [comment]
#365 was closed in favor of #379 which has been merged.

I don't see any extra functionality though, just how it's defined as an attribute (but I'm just starting to understand the code) so it would seem we still only have walk and strafe.

**Comment by caseyyee** [comment]
We can close this for now and file the other inputs as separate issues.
Jump will also require some thought since this could be part of a physics implementation.   Also another issue.
