### ISSUE TITLE
If you don't specify "from" parameter for animation, alternate animation won't work

### ISSUE THREAD

**Issue by fernandojsg** [aframevr/aframe-core#630]
If you try to animate an attribute with ```direction=alternate```, for example scale or position, you must specify the ```from``` value. Otherwise it will just go forwards and won't come back.

For example from the ```cursor``` example:
This go to from X=0 -> 15 -> 0.
```html
<a-entity position="3.5 1 0" rotation="0 45 0">
  <a-entity mixin="cube blue">
    <a-animation begin="click" fill="forwards" repeat="1"
                 direction="alternate" attribute="position" from="0 0 0"
                 to="15 0 0" dur="2000"></a-animation>
  </a-entity>
</a-entity>
```

But if I remove the attribute ```from="0 0 0"``` I expected to get that as a default value and to work the same way as before, but it just go from X=0 -> 15 and just stay there.
The same happens if you try to animate scale where the ```from``` value is the default value (1,1,1).
```html
<a-entity position="3.5 1 0" rotation="0 45 0">
  <a-entity mixin="cube blue">
    <a-animation begin="click" fill="forwards" repeat="1"
                 direction="alternate" attribute="position"
                 to="15 0 0" dur="2000"></a-animation>
  </a-entity>
</a-entity>
```

**Comment by dmarcos** [comment]
Fixed
