### ISSUE TITLE
Enter VR button disappears with no modal when clicked in non-VR browser

### ISSUE THREAD

**Issue by caseyyee** [aframevr/aframe-core#685]

**Comment by cvan** [comment]
This was a known issue - intended to be fixed by #56 but wasn't/isn't yet

**Comment by caseyyee** [comment]
Actually, this is some other issue.  The enter VR button was disappearing along with the modals for setup/viewing VR.      Though, I can't seem to reproduce it again :/    Will close for now and reopen if I encounter it again.
