### ISSUE TITLE
Publish GitHub Pages or remove links in README

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-core#689]
I know we deleted the `gh-pages` branch so the checkouts would be smaller, but we're referencing the GitHub Pages URLs in the [README](https://github.com/aframevr/aframe-core#downloads).

**Comment by cvan** [comment]
@dmarcos: thoughts?

**Comment by cvan** [comment]
Also worth noting that we're linking to https://aframe.io/aframe-core/examples/_images/pano/louvre.jpg (which is a 404) as image URLs in the code snippets at the bottom of https://aframe.io/docs/primitives/a-image.html

We could easily change them to a different pano image - just thought I'd call this out.

**Comment by sirkitree** [comment]
Just noticed https://aframevr.github.io/aframe-core/examples/ being linked to as well which is a 404 under "Also, be sure to check out these awesome examples:"

Looks like a lot of this README is duplicated under https://github.com/aframevr/aframe

**Comment by dmarcos** [comment]
I would love to have the gh-pages with core only examples. Do you think there will be confusing with http://aframe.io/ ?

**Comment by cvan** [comment]
it would live at https://aframe.io/aframe-core/ if you run `npm run ghpages` - I'm cool with that

**Comment by cvan** [comment]
@dmarcos you cool with this? can we push?

**Comment by cvan** [comment]
@dmarcos can we push these to GH Pages? I'm finding myself wanting to link people to aframe-core examples often but can't because they're not live.

**Comment by dmarcos** [comment]
sure!

**Comment by dmarcos** [comment]
Published:

https://aframe.io/aframe-core/examples/
