### ISSUE TITLE
allow components to specify the main value

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe-core#717]
If a component property in the schema is specified as `main: true`, then when a flat value is passed (attribute does not any colons or semicolons), then that property will take the value

for example with position we can do

```
schema: {
  position: { default: {xyz}, main: true}
}
```

to enable us to still do `position="0 1 2"`

for example to enhance geometry

```
schema: {
  primitive: { main: true }
}
```

then we can do ```geometry="cube"```. or with material we can do ```material="blue"```

**Comment by dmarcos** [comment]
may be. the problem is that it's not obvious anymore what it's going to happen. and if you adds mixins to the equation can get hairy

**Comment by ngokevin** [comment]
yeah maybe you're right. just trying to piece together what's needed to get out-of-the-box coordinate properties

**Comment by ngokevin** [comment]
This will be too messy.
