### ISSUE TITLE
allow specifying `id` on entities, which sets object3d name

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe-core#726]
- fits more into the ECS model where each entity has a unique identifier
- allows users to add semantics to their markup `<a-entity id="lightsaber-handle"></a-entity>`

**Comment by dmarcos** [comment]
object3s have already an uuid. you can assign ids to the '''a-entity''' elements and query for them. Why do we want to also add it to the object3d name?

**Comment by ngokevin** [comment]
hmm yeah
