### ISSUE TITLE
Animation loading busted

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-core#739]
Did some bisecting and it looks to be caused by a8a4f06

http://localhost:9000/examples/animation-aframe-logo/

## before
<img width="1401" alt="screenshot 2015-12-21 20 30 26" src="https://cloud.githubusercontent.com/assets/203725/11945817/b7c24422-a821-11e5-85e3-eb58c2838517.png">

## after
<img width="1401" alt="screenshot 2015-12-21 20 30 37" src="https://cloud.githubusercontent.com/assets/203725/11945816/b7c1922a-a821-11e5-8c18-255f2f608867.png">

**Comment by ngokevin** [comment]
A good hunch, I think this is an aframe issue. Elements in Aframe needs to match aframe-core and wait for all of its children to load before firing load.

**Comment by ngokevin** [comment]
Will be much better once primitives become entities.

**Comment by ngokevin** [comment]
fixed https://github.com/aframevr/aframe/pull/329

**Comment by cvan** [comment]
> Will be much better once primitives become entities.

keep in mind this will be an issue for anyone extending our `<a-entity>`, not just our templates/primitives implementation.

**Comment by cvan** [comment]
fixed, thanks:

<img width="1401" alt="screenshot 2015-12-21 22 41 45" src="https://cloud.githubusercontent.com/assets/203725/11947397/1b1eba34-a834-11e5-92ee-de347c61247a.png">
