### ISSUE TITLE
radiusTop, radiusBottom no longer work for cylinder geometry

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-core#741]
regressed with https://github.com/aframevr/aframe-core/commit/9a8ab575#diff-8b1e057bd151892d8ced8a81e26b5ebbL134

reported on Slack @ https://aframevr.slack.com/archives/learning/p1450754060000471

**Comment by dmarcos** [comment]
There are now two primitives: 
```cylinder``` that takes a radius and height  ```cone``` that takes a radiusTop, radiusBottom and height
https://github.com/aframevr/aframe-core/blob/master/src/components/geometry.js#L123
The templates have to reflect the new API
