### ISSUE TITLE
View a-video on mobile

### ISSUE THREAD

**Issue by joshkpeterson** [aframevr/aframe-core#775]
When viewing the example in the package at examples/template-video/index.html on mobile devices, all I see is a black rectangle where the video should be.

Chrome 47.0.2526.83 on Android 5.1.1 Samsung Note 5
Safari on iOS 9.0.2 on iPhone 6 

There are no javascript errors when running this on Android Chrome. 

The example at http://threejs.org/examples/#canvas_materials_video is giving me similar results, perhaps I should escalate to threejs? (Edit: created an [issue there too](https://github.com/mrdoob/three.js/issues/7932))

I've tried a bunch of different video file formats on different browsers/devices, and results are very uneven and scattered, but I couldn't get any video files to work on mobile whatsoever except I got this example to work in firefox on Android.

I could list out everything I've tried, but since sharing and working with video files is kind of cumbersome, let's see if we can get *just this one* video file to work on mobile chrome/safari first. 

Thanks!

**Comment by cvan** [comment]
Thanks for the detailed issue. Unfortunately, this is a known issue. See original issue filed here: aframevr/aframe#316.

It has to do with Chrome for Android disabling `<video>` autoplay by default; you have to play a video upon a user-initiated event. We'd love if the platform just supported it out of the box, but likely for some time things aren't going to change. In the meantime, I'm going to introduce a "play" button that will start the videos that are detected on the page (if any).

**Comment by joshkpeterson** [comment]
Whoops thanks, that slipped by me. It would be great to have a little documentation or example on how to incorporate user input to trigger a play on a video, I tried quickly but must have had something wrong.
